# Generated by Django 5.2 on 2025-04-27 02:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('attendance', models.IntegerField(blank=True, null=True)),
                ('arena', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_win_probability', models.FloatField()),
                ('prediction_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('home_team_advantage', models.TextField(blank=True)),
                ('away_team_advantage', models.TextField(blank=True)),
                ('relevant_factors', models.TextField(blank=True)),
                ('actual_result', models.BooleanField(blank=True, null=True)),
                ('was_correct', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='predictor_api.game')),
            ],
            options={
                'ordering': ['-prediction_time'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='predictor_api.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='predictor_api.team'),
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(default='2024-2025', max_length=9)),
                ('mp', models.FloatField(default=0)),
                ('fg', models.FloatField(default=0)),
                ('fga', models.FloatField(default=0)),
                ('fg_pct', models.FloatField(default=0)),
                ('fg3', models.FloatField(default=0)),
                ('fg3a', models.FloatField(default=0)),
                ('fg3_pct', models.FloatField(default=0)),
                ('fg2', models.FloatField(default=0)),
                ('fg2a', models.FloatField(default=0)),
                ('fg2_pct', models.FloatField(default=0)),
                ('ft', models.FloatField(default=0)),
                ('fta', models.FloatField(default=0)),
                ('ft_pct', models.FloatField(default=0)),
                ('orb', models.FloatField(default=0)),
                ('drb', models.FloatField(default=0)),
                ('trb', models.FloatField(default=0)),
                ('ast', models.FloatField(default=0)),
                ('stl', models.FloatField(default=0)),
                ('blk', models.FloatField(default=0)),
                ('tov', models.FloatField(default=0)),
                ('pf', models.FloatField(default=0)),
                ('pts', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='predictor_api.team')),
            ],
            options={
                'verbose_name_plural': 'Team Stats',
                'unique_together': {('team', 'season')},
            },
        ),
    ]
